Revert "Upgrade the base AMI from Debian Bookworm to Debian Trixie"
This reverts commit 757fa444716154ce6dd0a14f797aeafad7015aab.

Debian Trixie has Python 3.13, but gophish will only run on Python
3.11 or earlier.  When one attempts to do so the version of the
urllib3 Python library that gophish requires fails to import with:
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'